-- ============================================================
-- DATABASE SCHEMA
-- H2-compatible schema used before data.sql during application startup.
-- Hibernate validation is intentionally disabled in production startup so
-- schema.sql is the single source of truth for the demo database.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    full_name VARCHAR(100),
    badge_number VARCHAR(30),
    department VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number VARCHAR(30) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    location VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE,
    crime_type VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(20),
    incident_date TIMESTAMP NOT NULL,
    reported_date TIMESTAMP,
    created_by BIGINT,
    lead_investigator BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cases_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_cases_lead_investigator FOREIGN KEY (lead_investigator) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    evidence_number VARCHAR(30) UNIQUE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    type VARCHAR(30) NOT NULL,
    file_path VARCHAR(500),
    file_name VARCHAR(200),
    file_size BIGINT,
    mime_type VARCHAR(100),
    collected_at TIMESTAMP,
    location VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE,
    chain_of_custody TEXT,
    tags TEXT,
    forensic_notes TEXT,
    is_key_evidence BOOLEAN DEFAULT FALSE,
    uploaded_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evidence_case FOREIGN KEY (case_id) REFERENCES cases(id),
    CONSTRAINT fk_evidence_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS witnesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    name VARCHAR(100),
    age INTEGER,
    contact VARCHAR(100),
    address TEXT,
    witness_type VARCHAR(30),
    statement TEXT NOT NULL,
    statement_date TIMESTAMP,
    keywords TEXT,
    entities TEXT,
    contradictions TEXT,
    credibility_score DOUBLE,
    sentiment_score DOUBLE,
    suspicious_flags TEXT,
    nlp_analyzed BOOLEAN DEFAULT FALSE,
    recorded_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_witnesses_case FOREIGN KEY (case_id) REFERENCES cases(id),
    CONSTRAINT fk_witnesses_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS suspects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    alias VARCHAR(100),
    age INTEGER,
    description TEXT,
    photo_path VARCHAR(500),
    last_known_location VARCHAR(255),
    last_seen_latitude DOUBLE,
    last_seen_longitude DOUBLE,
    status VARCHAR(30),
    probability_score DOUBLE DEFAULT 0,
    evidence_match_score DOUBLE DEFAULT 0,
    proximity_score DOUBLE DEFAULT 0,
    timeline_score DOUBLE DEFAULT 0,
    behavior_score DOUBLE DEFAULT 0,
    movement_path TEXT,
    predicted_path TEXT,
    criminal_record TEXT,
    notes TEXT,
    added_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_suspects_case FOREIGN KEY (case_id) REFERENCES cases(id),
    CONSTRAINT fk_suspects_added_by FOREIGN KEY (added_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50),
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_locations_case FOREIGN KEY (case_id) REFERENCES cases(id)
);

CREATE TABLE IF NOT EXISTS timeline_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    event_time TIMESTAMP NOT NULL,
    phase VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    event_type VARCHAR(50),
    related_evidence_id BIGINT,
    related_suspect_id BIGINT,
    related_witness_id BIGINT,
    latitude DOUBLE,
    longitude DOUBLE,
    confidence_level DOUBLE DEFAULT 50,
    source VARCHAR(100),
    is_verified BOOLEAN DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_timeline_case FOREIGN KEY (case_id) REFERENCES cases(id),
    CONSTRAINT fk_timeline_evidence FOREIGN KEY (related_evidence_id) REFERENCES evidence(id),
    CONSTRAINT fk_timeline_suspect FOREIGN KEY (related_suspect_id) REFERENCES suspects(id),
    CONSTRAINT fk_timeline_witness FOREIGN KEY (related_witness_id) REFERENCES witnesses(id),
    CONSTRAINT fk_timeline_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS ai_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    insight_type VARCHAR(50) NOT NULL,
    title VARCHAR(200),
    content TEXT NOT NULL,
    severity VARCHAR(20),
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    confidence DOUBLE,
    is_dismissed BOOLEAN DEFAULT FALSE,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_insights_case FOREIGN KEY (case_id) REFERENCES cases(id)
);
